FROM golang:1.13

ENV CGO_ENABLED=0
ENV GO111MODULE=on

RUN mkdir /example-kube
ADD . /example-kube
WORKDIR /example-kube
RUN go build -o bin/provider ./istio-example/provider/main.go

FROM alpine:3.10

COPY --from=0 /example-kube/bin/provider .

ENTRYPOINT ["/provider"]
EXPOSE 8080