FROM golang:1.13

ENV CGO_ENABLED=0
ENV GO111MODULE=on

RUN mkdir /example-kube
ADD . /example-kube
WORKDIR /example-kube
RUN go build -o bin/consumer ./istio-example/consumer/main.go

FROM alpine:3.10

COPY --from=0 /example-kube/bin/consumer .

ENTRYPOINT ["/consumer"]
EXPOSE 8081