FROM golang:1.13

ENV GO111MODULE=on

RUN mkdir /example-kube
ADD . /example-kube
WORKDIR /example-kube
RUN go build -o bin/consumer ./istio-example/consumer/main.go

FROM alpine:3.10

RUN mkdir /app
COPY --from=0 /example-kube/bin/consumer /app/consumer
ENTRYPOINT ["/app/consumer"]
EXPOSE 8081