apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: admission-webhook
  name: admission-webhook
  labels:
    app: admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhook
  template:
    spec:
      containers:
        - name: admission-webhook
          image: admission-webhook:1.0
          args:
            - -tls-cert-file
            - /etc/webhook/certs/cert.pem
            - -tls-private-key-file
            - /etc/webhook/certs/key.pem
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-example-certs
---
apiVersion: v1
kind: Service
metadata:
  namespace: admission-webhook
  name: admission-webhook
  labels:
    app: admission-webhook
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: admission-webhook